# All copy for the site, one dict per language. Keys match in both.
HU = dict(
  lang="hu", locale="hu_HU", path="/",
  title="Rita Ovari – Coach és tréner | Csapatépítés, agilis workshopok, coaching Budapest",
  desc="Okleveles tréner és coach 5+ év tapasztalattal. Agilis workshopok, csapatépítés, csapat- és személyes coaching multinacionális cégeknek, startupoknak és magánszemélyeknek – magyarul és angolul, online vagy Budapesten.",
  skip="Ugrás a tartalomra",
  nav=[("szolgaltatasok","Szolgáltatások"),("modszer","Módszer"),("rolam","Rólam"),("gyik","GYIK"),("kapcsolat","Kapcsolat")],
  cta_short="Ingyenes konzultáció",
  hero_label="Coach · Tréner · Facilitátor — magyarul és angolul",
  hero_h1=("Mozduljunk","együtt."), drag_hint="← húzd a cetliket", pick="+ Ezt kérem", picked="✓ Kiválasztva",
  tray_txt="kiválasztva", tray_btn="Ajánlatot kérek", tray_prefill="Ezek érdekelnek:",
  hero_lead="Agilis workshopok, csapatépítés és személyre szabott coaching multinacionális cégeknek, startupoknak és mindenkinek, aki kész a következő lépésre.",
  cta_primary="Foglalj ingyenes konzultációt", cta_secondary="Workshopok és tréningek",
  floats=[("5+ év","tréneri tapasztalat"),("HU · EN","kétnyelvű alkalmak"),("Agilis","módszerek")],
  facts=["Okleveles tréner","5+ év tapasztalat","Magyarul és angolul","Online és Budapesten","Agilis eszköztár","Személyre szabott programok"],
  aud_label="Kinek szól",
  aud_h2='Három irány, egy <em class="ac">közös</em> cél.',
  aud_lead="Akár egy nemzetközi csapatot vezetsz, akár egy gyorsan növő startupot, akár a saját következő lépésedet keresed: a programot hozzád igazítom.",
  aud=[("butter","Multinacionális cégek","Nemzetközi csapatok, közös nyelv, szó szerint is. Tréningek és workshopok, amelyek illeszkednek a sprintjeitekhez és a vállalati kultúrátokhoz.","Csapatok · HR · L&D"),
       ("tulip","Startupok","Gyorsan nőtök? Segítek, hogy a csapat ne csak gyors, hanem összehangolt is legyen: retrók, szerepek, közös működési szabályok.","Alapítók · Csapatvezetők"),
       ("leaf","Magánszemélyek","Karrierváltás, új vezetői szerep vagy elakadás. Személyes coaching a saját tempódban, magyarul vagy angolul.","1:1 coaching")],
  srv_label="Szolgáltatások",
  srv_h2='Válassz a <em class="ac">tábláról.</em>',
  srv_lead="Minden kártya egy kiindulópont. Az ingyenes konzultáció után ezekből rakjuk össze a ti programotokat.",
  cols=[("Csapatoknak",[("n-butter","Csapatépítés, ami megmarad","Játékos, agilis alapú napok, amelyek után új közös rituálék maradnak, nem csak emlékek."),
                         ("n-butter","Csapatcoaching","Folyamatkísérés, amikor a jó hangulat már nem elég: bizalom, felelősség, közös döntéshozatal.")]),
        ("Workshopok és tréningek",[("n-tulip","Retró- és sprint-workshopok","Facilitált alkalmak a valódi backlogotok köré építve, hogy a megbeszélésekből döntés legyen."),
                         ("n-tulip","Agilis tréningek","Scrum és Kanban a gyakorlatban: szerepek, események, eszközök, kézzelfogható feladatokkal."),
                         ("n-tulip","Egyedi tréningek","Kommunikáció, visszajelzés, konfliktuskezelés, a csapatotok helyzetére szabva.")]),
        ("Neked",[("n-leaf","Személyes coaching","1:1 folyamat céltisztázással, kéthetente, online vagy személyesen."),
                  ("n-corn","Vezetői coaching","Új és tapasztalt vezetőknek: delegálás, visszajelzés, a saját vezetői stílus megtalálása.")])],
  formats=["Online","Budapesten, helyszínen","Fél- és egésznapos","Magyarul vagy angolul"],
  proc_label="Módszer",
  proc_h2='Így dolgozunk <em class="ac">együtt.</em>',
  steps=[("Ingyenes konzultáció","30 perces beszélgetés: mi a cél, ki vesz részt, és mi számít sikernek."),
         ("Tervezés","Egyedi programot állítok össze a helyzetetekre, nem dobozos tréninget."),
         ("Sprint","Workshopok, tréningek vagy coaching-alkalmak, sok gyakorlással és kevés diával."),
         ("Retró és utánkövetés","Megnézzük, mi változott, mi működik, és mi legyen a következő lépés.")],
  about_label="Rólam",
  about_h2='Szia, Rita <em class="ac">vagyok.</em>',
  about_p=["Okleveles tréner és coach vagyok, több mint öt éve tervezek és tartok tréningeket nemzetközi vállalati környezetben. Az agilis módszerekből azt hozom a terembe, ami tényleg működik: rövid ciklusokat, átlátható célokat és rendszeres visszajelzést.",
           "Magyarul és angolul is dolgozom, így a vegyes, nemzetközi csapatokban is mindenki otthon érezheti magát. Minden programot személyre szabok: előbb megértem a csapatot vagy az embert, és csak utána választok módszert."],
  creds=["Okleveles tréner","5+ év vállalati tréningtapasztalat","Agilis módszerek a gyakorlatban","Kétnyelvű: magyar és angol"],
  off_label="Munkán kívül",
  off=["Hastánc","Búvárkodás","Urbex","Utazás"],
  off_note="Ritmus, mélység és kíváncsiság. Ezt hozom a workshopokra is.",
  photo_cap="Ide kerül Rita fotója",
  out_label="Eredmények",
  out_h2='Amit a csapatok <em class="ac">hazavisznek.</em>',
  outs=[("01","Közös működési szabályok, amelyeket a csapat maga alkotott meg."),
        ("02","Rövidebb, fókuszáltabb megbeszélések és valódi döntések."),
        ("03","Bátrabb visszajelzés és világosabb felelősségek."),
        ("04","Személyes akcióterv minden résztvevőnek.")],
  faq_label="GYIK",
  faq_h2='Gyakori <em class="ac">kérdések.</em>',
  faq_lead="Nem találod a választ? Írj nyugodtan, szívesen segítek.",
  faqs=[("Milyen nyelven zajlanak az alkalmak?","Magyarul vagy angolul. Vegyes, nemzetközi csapatoknál akár mindkét nyelven, ahogy a csoportnak a legkényelmesebb."),
        ("Online vagy személyesen dolgozol?","Mindkettő működik. Online bárhonnan, személyesen Budapesten és környékén. Más helyszín egyeztetés alapján lehetséges."),
        ("Mennyibe kerül egy program?","Minden program egyedi, ezért nincs fix árlista. Az ingyenes konzultáció után pontos, írásos ajánlatot küldök."),
        ("Mennyi ideig tart egy coaching-folyamat?","Ez a céltól függ. Az első beszélgetésen közösen döntjük el az alkalmak számát és gyakoriságát."),
        ("Mi a különbség a csapatépítés és a csapatcoaching között?","A csapatépítés közös élmény és kapcsolódás, jellemzően egy-két nap. A csapatcoaching hosszabb folyamat, amely konkrét működési elakadásokon dolgozik."),
        ("Kell agilis tapasztalat a részvételhez?","Nem. Az agilis eszközöket mindig a csapat szintjéhez igazítom, a kezdőktől a tapasztalt Scrum-csapatokig.")],
  ct_label="Kapcsolat",
  ct_h2='Kezdjük egy <em class="ac">beszélgetéssel.</em>',
  ct_lead="Írd meg röviden, miben segíthetek, és egyeztetünk egy időpontot az ingyenes, 30 perces konzultációhoz.",
  ct_loc="Budapest · online",
  f_who="Kinek szól?", f_who_opts=["Cégnek / csapatnak","Magamnak"],
  f_name="Név", f_email="E-mail", f_company="Cég (nem kötelező)",
  f_topic="Miben segíthetek?", f_topics=["Workshop vagy tréning","Csapatépítés","Csapatcoaching","Személyes vagy vezetői coaching","Még nem tudom"],
  f_lang="Az alkalom nyelve", f_langs=["Magyar","Angol"],
  f_msg="Üzenet", f_msg_ph="Pár mondat a helyzetről, a csapatról vagy a célról…",
  f_send="Üzenet küldése", f_note="Az adataidat csak a kapcsolatfelvételhez használom.",
  f_ok="Köszönöm! Hamarosan válaszolok.",
  f_preview="Ez egy előnézet, az üzenet nem lett elküldve.",
  foot="Coaching · Tréning · Csapatépítés · Budapest",
  privacy="Adatvédelem",
  switch_label="Nyelv",
)

EN = dict(
  lang="en", locale="en_US", path="/en/",
  title="Rita Ovari – Coach & Trainer | Team Building, Agile Workshops, Coaching in Budapest",
  desc="Certified trainer and coach with 5+ years of experience. Agile workshops, team building, team and personal coaching for multinationals, startups and individuals – in English and Hungarian, online or in Budapest.",
  skip="Skip to content",
  nav=[("services","Services"),("approach","Approach"),("about","About"),("faq","FAQ"),("contact","Contact")],
  cta_short="Free discovery call",
  hero_label="Coach · Trainer · Facilitator — in English & Hungarian",
  hero_h1=("Move","together."), drag_hint="← drag the notes", pick="+ Add to my board", picked="✓ On my board",
  tray_txt="picked", tray_btn="Request a proposal", tray_prefill="I'm interested in:",
  hero_lead="Agile workshops, team building and personalised coaching for multinationals, startups and people ready for their next step.",
  cta_primary="Book a free discovery call", cta_secondary="Workshops & trainings",
  floats=[("5+ years","as a trainer"),("HU · EN","bilingual sessions"),("Agile","methods")],
  facts=["Certified trainer","5+ years of experience","English & Hungarian","Online & in Budapest","Agile toolkit","Personalised programmes"],
  aud_label="Who it's for",
  aud_h2='Three paths, one <em class="ac">shared</em> goal.',
  aud_lead="Whether you lead an international team, a fast-growing startup or you're looking for your own next step, I shape the programme around you.",
  aud=[("butter","Multinationals","International teams that need a common language, literally. Trainings and workshops that fit your sprints and your company culture.","Teams · HR · L&D"),
       ("tulip","Startups","Growing fast? I help your team become aligned as well as quick: retros, roles and shared working agreements.","Founders · Team leads"),
       ("leaf","Individuals","A career change, a new leadership role or feeling stuck. Personal coaching at your own pace, in English or Hungarian.","1:1 coaching")],
  srv_label="Services",
  srv_h2='Pick from the <em class="ac">board.</em>',
  srv_lead="Every card is a starting point. After the free discovery call, we build your programme from them.",
  cols=[("For teams",[("n-butter","Team building that sticks","Playful, agile-based days that leave your team with new rituals, not just memories."),
                      ("n-butter","Team coaching","A guided process for when good vibes aren't enough: trust, ownership, shared decisions.")]),
        ("Workshops & trainings",[("n-tulip","Retro & sprint workshops","Facilitated sessions built around your real backlog, so meetings end in decisions."),
                      ("n-tulip","Agile trainings","Scrum and Kanban in practice: roles, events and tools, with hands-on exercises."),
                      ("n-tulip","Custom trainings","Communication, feedback and conflict, tailored to your team's situation.")]),
        ("For you",[("n-leaf","Personal coaching","A 1:1 process with clear goals, every two weeks, online or in person."),
                    ("n-corn","Leadership coaching","For new and seasoned leaders: delegation, feedback and finding your own style.")])],
  formats=["Online","On-site in Budapest","Half & full day","English or Hungarian"],
  proc_label="Approach",
  proc_h2='How we work <em class="ac">together.</em>',
  steps=[("Free discovery call","A 30-minute talk: what's the goal, who's involved, and what does success look like."),
         ("Design","I build a programme for your situation. No off-the-shelf training."),
         ("Sprint","Workshops, trainings or coaching sessions, with lots of practice and few slides."),
         ("Retro & follow-up","We look at what changed, what works and what the next step should be.")],
  about_label="About",
  about_h2='Hi, I\'m <em class="ac">Rita.</em>',
  about_p=["I'm a certified trainer and coach, and for more than five years I've designed and delivered trainings in international corporate settings. From agile methods I bring into the room what actually works: short cycles, visible goals and regular feedback.",
           "I work in English and Hungarian, so everyone in a mixed, international team can feel at home. Every programme is personalised: I get to know the team or the person first, and only then choose the method."],
  creds=["Certified trainer","5+ years of corporate training","Agile methods in practice","Bilingual: English & Hungarian"],
  off_label="Off the clock",
  off=["Belly dance","Scuba diving","Urbex","Travel"],
  off_note="Rhythm, depth and curiosity. I bring the same into every workshop.",
  photo_cap="Rita's photo goes here",
  out_label="Outcomes",
  out_h2='What teams take <em class="ac">home.</em>',
  outs=[("01","Working agreements the team wrote for itself."),
        ("02","Shorter, sharper meetings that end in real decisions."),
        ("03","Braver feedback and clearer ownership."),
        ("04","A personal action plan for every participant.")],
  faq_label="FAQ",
  faq_h2='Frequently asked <em class="ac">questions.</em>',
  faq_lead="Can't find your answer? Just write to me, I'm happy to help.",
  faqs=[("What language are the sessions in?","English or Hungarian. With mixed, international teams we can use both, whatever works best for the group."),
        ("Do you work online or in person?","Both. Online from anywhere, in person in and around Budapest. Other locations by arrangement."),
        ("How much does a programme cost?","Every programme is tailored, so there's no fixed price list. After the free discovery call I send a detailed written proposal."),
        ("How long does a coaching process take?","It depends on the goal. We agree on the number and frequency of sessions together in the first conversation."),
        ("What's the difference between team building and team coaching?","Team building is a shared experience and connection, usually one or two days. Team coaching is a longer process that works on specific blockers in how the team operates."),
        ("Do participants need agile experience?","No. I adapt the agile tools to the team's level, from complete beginners to experienced Scrum teams.")],
  ct_label="Contact",
  ct_h2='Let\'s start with a <em class="ac">conversation.</em>',
  ct_lead="Tell me briefly how I can help, and we'll schedule your free 30-minute discovery call.",
  ct_loc="Budapest · online",
  f_who="Who is it for?", f_who_opts=["My company / team","Myself"],
  f_name="Name", f_email="Email", f_company="Company (optional)",
  f_topic="How can I help?", f_topics=["Workshop or training","Team building","Team coaching","Personal or leadership coaching","Not sure yet"],
  f_lang="Session language", f_langs=["English","Hungarian"],
  f_msg="Message", f_msg_ph="A few lines about your situation, team or goal…",
  f_send="Send message", f_note="Your details are only used to get back to you.",
  f_ok="Thank you! I'll get back to you soon.",
  f_preview="This is a preview, so the message wasn't sent.",
  foot="Coaching · Training · Team building · Budapest",
  privacy="Privacy",
  switch_label="Language",
)
